name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "refactor/**"
      - "hotfix/**"
      - "chore/**"
      - "docs/**"
      - "test/**"
      - "release/**"

jobs:
  test:
    name: Run tests and generate Jacoco report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run tests and generate coverage report
        run: mvn -B clean test jacoco:report

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          if-no-files-found: error
          retention-days: 15